# Generated by Django 3.2.5 on 2021-07-23 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profilemodel',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
