# Generated by Django 3.2.5 on 2021-07-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productmodel_long_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='productsizes',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='productsizes',
            field=models.ManyToManyField(related_name='products', to='products.ProductSizeModel'),
        ),
    ]
