# Generated by Django 3.2.5 on 2021-07-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210716_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'height',
                'verbose_name_plural': 'height',
            },
        ),
        migrations.CreateModel(
            name='WeightModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'weight',
                'verbose_name_plural': 'weight',
            },
        ),
        migrations.CreateModel(
            name='WidthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'width',
                'verbose_name_plural': 'width',
            },
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='productsizes',
        ),
        migrations.DeleteModel(
            name='ProductSizeModel',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='width',
            field=models.ManyToManyField(related_name='products', to='products.WidthModel'),
        ),
    ]
