# Generated by Django 3.2.5 on 2021-07-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210716_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='height',
            field=models.ManyToManyField(related_name='products', to='products.HeightModel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.ManyToManyField(related_name='products', to='products.WeightModel'),
        ),
    ]
