# Generated by Django 3.2.5 on 2021-07-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210716_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='height',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='height',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.heightmodel'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='weight',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.weightmodel'),
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='width',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='width',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.widthmodel'),
        ),
    ]
