# Generated by Django 3.2.5 on 2021-07-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_productmodel_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc1', models.CharField(max_length=20, verbose_name='description')),
                ('image', models.FileField(upload_to='home_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categorymodel', verbose_name='title_home')),
            ],
            options={
                'verbose_name': 'home',
                'verbose_name_plural': 'homes',
            },
        ),
    ]
