# Generated by Django 3.2.5 on 2021-07-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_categoryhomemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhomemodel',
            name='desc1',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='description'),
        ),
    ]
