# Generated by Django 3.2.5 on 2021-07-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_categoryhomemodel_desc1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryhomemodel',
            name='desc1',
            field=models.CharField(max_length=20, verbose_name='description'),
        ),
    ]
