# Generated by Django 3.2.5 on 2021-07-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_categoryhomemodel_desc1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryHomeModel',
        ),
    ]
