# Generated by Django 3.2.5 on 2021-07-28 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_delete_categoryhomemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryHomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('image', models.FileField(upload_to='home_cat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categorymodel', verbose_name='hone_cat')),
            ],
            options={
                'verbose_name': 'category home',
                'verbose_name_plural': 'category home',
            },
        ),
    ]
