# Generated by Django 3.2.5 on 2021-07-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_categoryhomemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryhomemodel',
            name='image',
        ),
    ]
