# Generated by Django 3.2.6 on 2021-08-14 04:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_auto_20210814_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='wishlist',
            field=models.CharField(max_length=90, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
