# Generated by Django 3.2.6 on 2021-10-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20210814_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='wishlist',
        ),
    ]
